import { expect, test } from "@playwright/test";

test("search, skin tones, recents and large live reactions", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Play a friend" }).click();
  await expect(page.getByText(/^(Your move\.|Over to them\.)$/)).toBeVisible();
  const otherContext = await browser.newContext({ viewport: { width: 393, height: 852 } });
  const other = await otherContext.newPage();
  await other.goto(page.url());
  await expect(other.getByText(/^(Your move\.|Over to them\.)$/)).toBeVisible();
  await page.getByRole("button", { name: "More emoji" }).click();
  await page.getByRole("textbox", { name: "Search emoji" }).fill("nothingmatchesxyz");
  await expect(page.getByText("No emoji found. Try another word.")).toBeVisible();
  await page.getByRole("button", { name: "People emoji" }).click();
  await page.getByRole("radio", { name: "Medium skin tone", exact: true }).click();
  await page.getByRole("textbox", { name: "Search emoji" }).fill("thumbs up");
  await expect(page.getByRole("button", { name: "Send thumbs up", exact: true })).toHaveText("👍🏽");
  await page.screenshot({ path: "test-results/emoji-picker.png" });
  await page.getByRole("button", { name: "Send thumbs up", exact: true }).click();
  await expect(page.getByTestId("reaction-burst")).toHaveText("👍🏽");
  await expect(other.getByTestId("reaction-burst")).toHaveText("👍🏽");
  const burst = other.getByTestId("reaction-burst");
  const box = await burst.boundingBox();
  expect(box!.width).toBeGreaterThan(150);
  expect(Math.abs(box!.x + box!.width / 2 - 393 / 2)).toBeLessThan(3);
  expect(Math.abs(box!.y + box!.height / 2 - 852 / 2)).toBeLessThan(3);
  await other.screenshot({ path: "test-results/emoji-burst.png" });
  await expect.poll(() => burst.evaluate((el) => Number(getComputedStyle(el).opacity))).toBeLessThan(0.8);
  expect(await burst.evaluate((el) => new DOMMatrix(getComputedStyle(el).transform).a)).toBeLessThan(1);
  await other.getByRole("button", { name: "Send Fire" }).click();
  await expect(page.getByTestId("reaction-burst")).toHaveText("🔥");
  await expect(page.getByTestId("reaction-burst")).toHaveCount(0);
  await expect(other.getByTestId("reaction-burst")).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("button", { name: "Send thumbs up", exact: true })).toHaveText("👍🏽");
  await page.getByRole("button", { name: "More emoji" }).click();
  await page.setViewportSize({ width: 320, height: 640 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: "test-results/emoji-picker-small.png" });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("textbox", { name: "Search emoji" })).not.toBeVisible();
  expect(errors).toEqual([]);
  await otherContext.close();
});

test("failed sends do not enter recents or animate, and reduced motion does not shrink", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await page.getByRole("button", { name: "Play a friend" }).click();
  await expect(page.getByText(/^(Your move\.|Over to them\.)$/)).toBeVisible();
  await page.route("**/api/games/*/react", (route) => route.fulfill({ json: { ok: false, error: "Test rejection" } }));
  await page.getByRole("button", { name: "Send Fire" }).click();
  await expect(page.getByRole("alert")).toContainText("didn’t send");
  await expect(page.getByTestId("reaction-burst")).toHaveCount(0);
  expect(await page.evaluate(() => localStorage.getItem("yourmove.recent-emojis"))).toBeNull();
  await page.unroute("**/api/games/*/react");
  await page.getByRole("button", { name: "Send Fire" }).click();
  const burst = page.getByTestId("reaction-burst");
  await expect(burst).toHaveText("🔥");
  await expect.poll(() => burst.evaluate((el) => Number(getComputedStyle(el).opacity))).toBeLessThan(0.8);
  expect(await burst.evaluate((el) => new DOMMatrix(getComputedStyle(el).transform).a)).toBe(1);
  await expect(burst).toHaveCount(0);
});
