import { expect, test } from "@playwright/test";

test("two players exchange moves and reactions, recover seats, and finish a game", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByText("Good company.")).toBeVisible();
  await page.screenshot({ path: "test-results/home.png", fullPage: true });
  await page.getByRole("button", { name: "Play a friend" }).click();
  await expect(page.getByText(/^(Your move\.|Over to them\.)$/)).toBeVisible();
  const gameURL = page.url();
  const opponentContext = await browser.newContext({ viewport: { width: 393, height: 852 } });
  const opponent = await opponentContext.newPage();
  opponent.on("pageerror", (error) => errors.push(error.message));
  await opponent.goto(gameURL);
  await expect(opponent.getByText(/^(Your move\.|Over to them\.)$/)).toBeVisible();
  const white = await page.getByText("Your move.", { exact: true }).isVisible() ? page : opponent;
  const black = white === page ? opponent : page;
  await expect(black.getByRole("button", { name: /^h1, white rook/ })).toBeVisible();
  const move = async (client: typeof page, from: string, to: string) => {
    await client.getByRole("button", { name: new RegExp("^" + from + ",") }).click();
    await client.getByRole("button", { name: new RegExp("^" + to + ",.*legal move") }).click();
  };
  await move(white, "f2", "f3");
  await expect(black.getByText("Your move.", { exact: true })).toBeVisible();
  await expect(black.getByRole("button", { name: "f3, white pawn", exact: true })).toBeVisible();
  await move(black, "e7", "e5");
  await expect(white.getByText("Your move.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Send Fire" }).click();
  await expect(opponent.getByText("Them", { exact: true })).toBeVisible();
  await opponent.getByRole("button", { name: "Send Applause" }).click();
  await expect(page.getByText("Them", { exact: true })).toBeVisible();
  await white.screenshot({ path: "test-results/game.png", fullPage: true });
  await page.getByRole("button", { name: "Appearance", exact: true }).click();
  await page.getByRole("radio", { name: "Lilac board" }).click();
  await page.getByRole("radio", { name: "Use dark theme" }).click();
  await page.reload();
  await expect(page.getByText(white === page ? "Your move." : "Over to them.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Appearance", exact: true }).click();
  await expect(page.getByRole("radio", { name: "Lilac board" })).toHaveAttribute("aria-checked", "true");
  await expect(page.getByRole("radio", { name: "Use dark theme" })).toHaveAttribute("aria-checked", "true");
  await page.getByRole("button", { name: "Close appearance" }).click();
  await expect(page.getByRole("radio", { name: "Use dark theme" })).not.toBeVisible();
  await expect(page.getByText(white === page ? "Your move." : "Over to them.", { exact: true })).toHaveCSS("color", "rgb(243, 244, 233)");
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: "test-results/game-dark.png", fullPage: true });
  await page.setViewportSize({ width: 393, height: 852 });
  const spectatorContext = await browser.newContext();
  const spectator = await spectatorContext.newPage();
  await spectator.goto(gameURL);
  await expect(spectator.getByText("Enjoy the game.")).toBeVisible();
  await expect(spectator.getByRole("button", { name: /^e2, white pawn/ })).toBeDisabled();
  await move(white, "g2", "g4");
  await expect(black.getByText("Your move.", { exact: true })).toBeVisible();
  await move(black, "d8", "h4");
  await expect(page.getByText("That’s a game.")).toBeVisible();
  await page.getByRole("button", { name: /Moves/ }).click();
  await expect(page.getByText("Qh4#", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Back to home" }).click();
  await expect(page.getByText("PICK UP WHERE YOU LEFT OFF")).toBeVisible();
  expect(errors).toEqual([]);
  await spectatorContext.close();
  await opponentContext.close();
});

test("small phones have no horizontal overflow and invalid invites stay disabled", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 640 });
  await page.goto("/");
  const appearance = page.getByRole("button", { name: "Appearance", exact: true });
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await expect(page.getByRole("radio", { name: "Lilac board" })).toHaveCount(0);
  const trigger = await appearance.boundingBox();
  expect(trigger!.y).toBeLessThan(60);
  expect(trigger!.x).toBeGreaterThan(230);
  await appearance.click();
  await page.getByRole("radio", { name: "Lilac board" }).click();
  await page.getByRole("radio", { name: "Use dark theme" }).click();
  await expect(page.getByText("Good company.")).toHaveCSS("color", "rgb(243, 244, 233)");
  await page.screenshot({ path: "test-results/appearance-dark.png", fullPage: true });
  await page.getByRole("button", { name: "Close appearance" }).click();
  await page.reload();
  await appearance.click();
  await expect(page.getByRole("radio", { name: "Lilac board" })).toHaveAttribute("aria-checked", "true");
  await expect(page.getByRole("radio", { name: "Use dark theme" })).toHaveAttribute("aria-checked", "true");
  await page.getByRole("radio", { name: "Use light theme" }).click();
  await expect(page.getByText("Good company.")).toHaveCSS("color", "rgb(37, 43, 40)");
  await page.keyboard.press("Escape");
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await appearance.click();
  await page.getByRole("button", { name: "Dismiss appearance" }).click({ position: { x: 10, y: 500 } });
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await page.getByRole("textbox", { name: "Game link or ID" }).fill("not a chess link");
  await expect(page.getByRole("button", { name: "Join game" })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: "test-results/small-phone.png", fullPage: true });
});
