import { test, expect } from "@playwright/test";

test("computer picker starts a recoverable bot game and protects the reserved seat", async ({ page, browser, request }) => {
 await page.goto("/");
 await page.getByRole("button", { name: "Play the computer" }).click();
 await expect(page.getByRole("dialog")).toBeVisible();
 await expect(page.getByRole("radio", { name: /Pip/ })).toBeChecked();
 await page.getByLabel("Black", { exact:true }).check();
 await page.getByRole("button", { name: "Let’s play" }).click();
 await expect(page).toHaveURL(/\/g\//);
 await expect(page.locator(".player-info strong", { hasText: "Pip" })).toBeVisible();
 await expect(page.getByTestId("pgn")).toContainText("1.", {timeout:20000});
 await expect(page.getByTestId("turn")).toContainText("Your turn");
 const id = new URL(page.url()).pathname.split("/").at(-1)!;
 const snapshot = await request.get(`/api/games/${id}/snapshot?clientId=test-spectator`);
 const state = await snapshot.json();
 expect(state.role).toBe("spectator"); expect(state.bot.id).toBe("pip"); expect(state.uci).toHaveLength(1);
 const rejected = await request.post(`/api/games/${id}/move`, {data:{clientId:"test-spectator", uci:"e7e5", botMove:true, expectedPly:1}});
 expect((await rejected.json()).ok).toBe(false);
 // The real human move uses the same command endpoint as friend games.
 const cid = await page.evaluate(() => localStorage.getItem("tinychess:clientId"));
 const moved = await request.post(`/api/games/${id}/move`, { data:{clientId:cid, uci:"e7e5"} });
 expect((await moved.json()).ok).toBe(true);
 await expect.poll(async () => (await (await request.get(`/api/games/${id}/snapshot?clientId=test-spectator`)).json()).uci.length, {timeout:20000}).toBe(3);
 await page.reload();
 await expect(page.getByTestId("turn")).toContainText("Your turn");
 await expect(page.locator(".player-info strong", {hasText:"Pip"})).toBeVisible();
 const spectator = await browser.newPage();
 await spectator.goto(page.url());
 await expect(spectator.getByText("Watching", {exact:true})).toBeVisible();
 await spectator.close();
 await page.getByRole("link", { name: "Your Move home" }).click();
 await expect(page.locator(".recent-games").getByText("PvBot", { exact:true })).toBeVisible();
 await expect(page.locator(".recent-games").getByText("A match with Pip")).toBeVisible();
});

test("advanced settings run two selected bots at the chosen pace and resume after reload", async ({ page, browser, request }) => {
 const submittedAt: number[] = [];
 page.on("request", req => { if (req.method() === "POST" && req.url().endsWith("/move")) submittedAt.push(Date.now()); });
 await page.goto("/");
 await page.getByRole("button", { name: "Play the computer" }).click();
 await page.getByText("Advanced settings", { exact: true }).click();
 await page.getByRole("checkbox", { name: "Bot vs. bot" }).check();
 await page.getByLabel("Black bot", { exact: true }).selectOption("ada");
 await page.getByLabel("White bot", { exact: true }).selectOption("max");
 await page.getByRole("slider", { name: "Time between moves" }).fill("1000");
 await expect(page.locator(".bot-delay output")).toHaveText("1 s");
 await page.getByRole("button", { name: "Start bot battle" }).click();
 await expect(page).toHaveURL(/\/g\//);
 const url = page.url();
 const id = new URL(url).pathname.split("/").at(-1)!;
 const snapshot = async () => (await (await request.get(`/api/games/${id}/snapshot?clientId=battle-spectator`)).json());
 await expect(page.locator(".player-info strong", { hasText: "Max" })).toBeVisible();
 await expect(page.locator(".player-info strong", { hasText: "Ada" })).toBeVisible();
 await expect(page.getByText("Watching", { exact: true })).toBeVisible();
 await expect.poll(async () => (await snapshot()).uci.length, { timeout: 30000 }).toBeGreaterThanOrEqual(4);
 expect(submittedAt.length).toBeGreaterThanOrEqual(4);
 for (let i = 1; i < submittedAt.length; i++) expect(submittedAt[i] - submittedAt[i - 1]).toBeGreaterThanOrEqual(950);
 const before = await snapshot();
 expect(before.bot).toMatchObject({ id: "ada", color: "b", playerBotId: "max", moveDelayMs: 1000 });
 await page.reload();
 await expect.poll(async () => (await snapshot()).uci.length, { timeout: 20000 }).toBeGreaterThan(before.uci.length);
 await page.goto("/");
 await expect(page.locator(".recent-games").getByText("Bot vs. bot", { exact: true })).toBeVisible();
 await expect(page.locator(".recent-games").getByText("Max vs. Ada")).toBeVisible();
 const spectator = await browser.newPage();
 await spectator.goto(url);
 await expect(spectator.getByText("Watching", { exact: true })).toBeVisible();
 const stopped = await snapshot();
 await spectator.waitForTimeout(2200);
 expect((await snapshot()).uci).toEqual(stopped.uci);
 await spectator.close();
});
