import { expect, test } from "@playwright/test";

test("responsive home matches the mobile palette, accepts invites and persists themes", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: /Good company/ })).toBeVisible();
  const appearance = page.getByRole("button", { name: "Appearance", exact: true });
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await expect(page.getByRole("button", { name: "Lilac board" })).toHaveCount(0);
  await appearance.click();
  await page.getByRole("button", { name: "Lilac board" }).click();
  await page.reload();
  await appearance.click();
  await expect(page.getByRole("button", { name: "Lilac board" })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Matcha board" }).click();
  await page.getByRole("button", { name: "Close appearance" }).click();
  await page.screenshot({ path: "test-results/home-phone.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "test-results/home-desktop.png", fullPage: true });
  await appearance.click();
  await page.getByRole("button", { name: "Use dark theme" }).click();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await appearance.click();
  await page.screenshot({ path: "test-results/home-dark.png", fullPage: true });
  await page.getByRole("button", { name: "Use light theme" }).click();
  await page.keyboard.press("Escape");
  await expect(appearance).toBeFocused();
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await page.setViewportSize({ width: 320, height: 740 });
  await appearance.click();
  const panel = await page.getByRole("region", { name: "Appearance settings" }).boundingBox();
  expect(panel!.x).toBeGreaterThanOrEqual(0);
  expect(panel!.x + panel!.width).toBeLessThanOrEqual(320);
  await page.screenshot({ path: "test-results/appearance-small.png", fullPage: true });
  await page.mouse.click(8, 400);
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await appearance.focus();
  await page.keyboard.press("Enter");
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Close appearance" })).toBeFocused();
  await page.keyboard.press("Escape");
  await page.getByRole("textbox", { name: "Game link or ID" }).fill("not a game link");
  await expect(page.getByRole("button", { name: "Join game", exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.getByRole("textbox", { name: "Game link or ID" }).fill("https://chess.test/g/friendly-game?invite=1");
  await expect(page.getByRole("button", { name: "Join game", exact: true })).toBeEnabled();
});

test("two seats, correct black orientation, live emoji, checkmate, spectators and recent games", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Play a friend" }).click();
  await expect(page.locator("#turn")).toHaveText(/^(Your turn|Their turn)$/);
  await page.getByRole("button", { name: "Appearance", exact: true }).click();
  await page.getByRole("button", { name: "Use dark theme" }).click();
  await page.getByRole("button", { name: "Peach board" }).click();
  await page.getByRole("button", { name: "Close appearance" }).click();
  const gameURL = page.url();
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: "test-results/game-small.png", fullPage: true });
  await page.setViewportSize({ width: 393, height: 852 });
  const otherContext = await browser.newContext({ viewport: { width: 393, height: 852 } });
  const other = await otherContext.newPage();
  other.on("pageerror", (error) => errors.push(error.message));
  await other.goto(gameURL);
  await expect(other.locator("#turn")).toHaveText(/^(Your turn|Their turn)$/);
  const white = await page.locator("#turn").textContent() === "Your turn" ? page : other;
  const black = white === page ? other : page;
  await expect(black.locator("#board button").first()).toHaveAttribute("aria-label", "h1, white rook");
  const move = async (client: typeof page, from: string, to: string) => {
    await client.locator(`[data-square="${from}"]`).click();
    await expect(client.locator(`[data-square="${to}"]`)).toHaveAttribute("aria-label", /legal move/);
    await client.locator(`[data-square="${to}"]`).click();
  };
  await move(white, "f2", "f3");
  await expect(black.locator("#turn")).toHaveText("Your turn");
  await move(black, "e7", "e5");
  await expect(white.locator("#turn")).toHaveText("Your turn");
  await white.getByRole("button", { name: "Send 🔥", exact: true }).click();
  await expect(black.locator(".reaction-history")).toContainText("🔥Them");
  await black.getByRole("button", { name: "Send 👏", exact: true }).click();
  await expect(white.locator(".reaction-history")).toContainText("👏Them");
  await expect(white.locator(".big-emoji")).toHaveCount(0);
  await white.screenshot({ path: "test-results/game-phone.png", fullPage: true });
  await white.setViewportSize({ width: 1440, height: 1050 });
  await white.screenshot({ path: "test-results/game-desktop.png", fullPage: true });
  await white.reload();
  await expect(white.locator("#turn")).toHaveText("Your turn");
  const spectatorContext = await browser.newContext();
  const spectator = await spectatorContext.newPage();
  await spectator.goto(gameURL);
  await expect(spectator.getByText("The seats are full. You can watch and react.")).toBeVisible();
  await expect(spectator.locator('[data-square="e2"]')).toBeDisabled();
  await move(white, "g2", "g4");
  await expect(black.locator("#turn")).toHaveText("Your turn");
  await move(black, "d8", "h4");
  await expect(white.locator("#status")).toContainText("Checkmate");
  await expect(white.locator("#pgn")).toContainText("Qh4#");
  await white.getByRole("link", { name: "Your Move home" }).click();
  await expect(white.getByText("PICK UP WHERE YOU LEFT OFF")).toBeVisible();
  expect(errors).toEqual([]);
  await spectatorContext.close();
  await otherContext.close();
});
